openapi: 3.0.3
info:
  description: This is a set of interfaces based on the OpenAPI 3.0 specification
    for a wrapper client
  title: Swagger HIP Facade - OpenAPI 3.0
  version: 1.0.0
servers:
- url: http://localhost:8082/v1
paths:
  /add-patients:
    put:
      description: Insert or Update a list of patients
      operationId: upsertPatients
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Patient'
              type: array
        description: Insert or update a list of patients in the wrapper database
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacadeResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Insert or Update a list of patients
      tags:
      - patients
      x-content-type: application/json
      x-accepts: application/json
  /sms/notify:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsNotify'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacadeResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Sending sms to patient via ABDM
      tags:
      - patients
      x-content-type: application/json
      x-accepts: application/json
  /patient-discover:
    post:
      description: |
        Request for patient care context discover, made by CM for a specific HIP. It is expected that HIP will subsequently return either zero or one patient record with (potentially masked) associated care contexts
          1. **At least one of the verified identifier matches**
          2. **Name (fuzzy), gender matches**
          3. **If YoB was given, age band(+-2) matches**
          4. **If unverified identifiers were given, one of them matches**
          5. **If more than one patient records would be found after aforementioned steps, then patient who matches most verified and unverified identifiers would be returned.**
          6. **If there would be still more than one patients (after ranking) error would be returned**
          7. **Intended HIP should be able to resolve and identify results returned in the subsequent link confirmation request via the specified transactionId**
          8. **Intended HIP should store the discovery results with transactionId and care contexts discovered for subsequent link initiation**
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientDiscoveryRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: |
            **Causes:**
              * Empty verified identifiers.
              * Format mismatch of any of attributes.
                | type   | Format/Allowed Values|
                | ------- | ----------------    |
                | gender  | M/F/O/U |
                | MOBILE  | valid mobile number with proper country code |
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: |
            **Causes:**
              * Unauthorized request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: |
            **Causes:**
              * Downstream system(s) is down.
              * Unhandled exceptions.
      summary: Discover patient's accounts
      tags:
      - patients
      x-content-type: application/json
      x-accepts: application/json
  /patient-care-contexts:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CareContextRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Gets Care Contexts of the given patient id
      tags:
      - patients
      x-content-type: application/json
      x-accepts: application/json
  /share/profile:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShareProfileRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileAcknowledgement'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Sharing patient details with a facility via scan and share
      tags:
      - patients
      x-content-type: application/json
      x-accepts: application/json
  /verify/otp:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_verify_otp_post_request'
        description: Verifies OTP
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestStatusResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: The Verification of otp in discovery flow
      tags:
      - discovery
      x-content-type: application/json
      x-accepts: application/json
  /request/otp:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_request_otp_post_request'
        description: requesting for OTP
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestStatusResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: The Initiating of otp in discovery flow
      tags:
      - discovery
      x-content-type: application/json
      x-accepts: application/json
  /verify-otp:
    post:
      description: Verify OTP for link auth modes Mobile and Aadhaar
      operationId: verifyOTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/verifyOTP_request'
        description: Verifies OTP
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacadeResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Verify OTP for link auth modes Mobile and Aadhaar
      tags:
      - link
      x-content-type: application/json
      x-accepts: application/json
  /link-carecontexts:
    post:
      description: Links care contexts for a given patient's abha address
      operationId: linkCareContexts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/linkCareContexts_request'
        description: Links Care Contexts
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacadeResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Links care contexts for a given patient's abha address
      tags:
      - link
      x-content-type: application/json
      x-accepts: application/json
  /link-status/{requestId}:
    get:
      parameters:
      - description: Request Id of the link care context request.
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestStatusResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Get status of Link request.
      tags:
      - link
      x-accepts: application/json
components:
  schemas:
    Patient:
      example:
        patientMobile: patientMobile
        gender: M
        patientReference: patientReference
        name: name
        dateOfBirth: 2003-09-23
        patientDisplay: patientDisplay
        careContexts:
        - referenceNumber: referenceNumber
          display: display
        - referenceNumber: referenceNumber
          display: display
        abhaAddress: abhaAddress
      properties:
        abhaAddress:
          type: string
        name:
          type: string
        gender:
          enum:
          - M
          - F
          - O
          - U
          example: M
          type: string
        dateOfBirth:
          example: 2003-09-23
          type: string
        patientReference:
          type: string
        patientDisplay:
          type: string
        patientMobile:
          type: string
        careContexts:
          items:
            $ref: '#/components/schemas/CareContext'
          type: array
      type: object
    CareContextRequest:
      example:
        hipId: hipId
        abhaAddress: abhaAddress
      properties:
        abhaAddress:
          type: string
        hipId:
          type: string
      type: object
    PatientWithCareContext:
      properties:
        id:
          description: ABHA Address
          type: string
        referenceNumber:
          type: string
        careContexts:
          items:
            $ref: '#/components/schemas/CareContext'
          type: array
      type: object
    CareContext:
      example:
        referenceNumber: referenceNumber
        display: display
      properties:
        referenceNumber:
          type: string
        display:
          type: string
      type: object
    RequestStatusResponse:
      example:
        linkRefNumber: linkRefNumber
        requestId: requestId
        error:
          code: 6
          message: message
        status: status
      properties:
        linkRefNumber:
          type: string
        requestId:
          type: string
        status:
          type: string
        error:
          $ref: '#/components/schemas/ErrorResponse'
      type: object
    FacadeResponse:
      example:
        code: 0
        clientRequestId: clientRequestId
        message: message
        error:
          code: 6
          message: message
      properties:
        clientRequestId:
          type: string
        code:
          type: integer
        message:
          type: string
        error:
          $ref: '#/components/schemas/ErrorResponse'
      type: object
    ErrorResponse:
      example:
        code: 6
        message: message
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    SmsNotify:
      example:
        notification:
          phoneNo: phoneNo
          hip:
            name: name
            id: id
        requestId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        requestId:
          format: uuid
          type: string
        timestamp:
          format: date-time
          type: string
        notification:
          $ref: '#/components/schemas/SmsNotify_notification'
      type: object
    ShareProfileRequest:
      example:
        hipId: hipId
        profile:
          requestId: requestId
          profile:
            hipCode: hipCode
            patient:
              address:
                pincode: pincode
                line: line
                district: district
                state: state
              gender: gender
              dayOfBirth: dayOfBirth
              identifiers:
              - type: type
                value: value
              - type: type
                value: value
              name: name
              healthId: healthId
              healthIdNumber: healthIdNumber
              monthOfBirth: monthOfBirth
              yearOfBirth: yearOfBirth
          location:
            latitude: latitude
            longitude: longitude
          intent:
            type: type
          timestamp: timestamp
        token: token
      properties:
        token:
          description: The token associated with the profile share
          type: string
        hipId:
          description: The facility associated with the profile share
          type: string
        profile:
          $ref: '#/components/schemas/ProfileShare'
      type: object
    ProfileAcknowledgement:
      example:
        tokenNumber: tokenNumber
        healthId: healthId
        status: status
      properties:
        status:
          description: The status of the profile acknowledgement
          type: string
        healthId:
          description: The health ID associated with the acknowledgement
          type: string
        tokenNumber:
          description: The token number associated with the acknowledgement
          type: string
      type: object
    ProfileShare:
      example:
        requestId: requestId
        profile:
          hipCode: hipCode
          patient:
            address:
              pincode: pincode
              line: line
              district: district
              state: state
            gender: gender
            dayOfBirth: dayOfBirth
            identifiers:
            - type: type
              value: value
            - type: type
              value: value
            name: name
            healthId: healthId
            healthIdNumber: healthIdNumber
            monthOfBirth: monthOfBirth
            yearOfBirth: yearOfBirth
        location:
          latitude: latitude
          longitude: longitude
        intent:
          type: type
        timestamp: timestamp
      properties:
        requestId:
          description: The request ID associated with the profile share
          type: string
        timestamp:
          description: The timestamp of the profile share
          type: string
        intent:
          $ref: '#/components/schemas/ProfileIntent'
        location:
          $ref: '#/components/schemas/ProfileLocation'
        profile:
          $ref: '#/components/schemas/PatientProfile'
      type: object
    ProfileIntent:
      example:
        type: type
      properties:
        type:
          description: The type of profile intent
          type: string
      type: object
    ProfileLocation:
      example:
        latitude: latitude
        longitude: longitude
      properties:
        latitude:
          description: The latitude of the profile location
          type: string
        longitude:
          description: The longitude of the profile location
          type: string
      type: object
    PatientProfile:
      example:
        hipCode: hipCode
        patient:
          address:
            pincode: pincode
            line: line
            district: district
            state: state
          gender: gender
          dayOfBirth: dayOfBirth
          identifiers:
          - type: type
            value: value
          - type: type
            value: value
          name: name
          healthId: healthId
          healthIdNumber: healthIdNumber
          monthOfBirth: monthOfBirth
          yearOfBirth: yearOfBirth
      properties:
        hipCode:
          description: The HIP code associated with the patient profile
          type: string
        patient:
          $ref: '#/components/schemas/PatientDetails'
      type: object
    PatientDetails:
      example:
        address:
          pincode: pincode
          line: line
          district: district
          state: state
        gender: gender
        dayOfBirth: dayOfBirth
        identifiers:
        - type: type
          value: value
        - type: type
          value: value
        name: name
        healthId: healthId
        healthIdNumber: healthIdNumber
        monthOfBirth: monthOfBirth
        yearOfBirth: yearOfBirth
      properties:
        healthId:
          description: The health ID of the patient
          type: string
        healthIdNumber:
          description: The health ID number of the patient
          type: string
        name:
          description: The name of the patient
          type: string
        gender:
          description: The gender of the patient
          type: string
        address:
          $ref: '#/components/schemas/PatientAddress'
        yearOfBirth:
          description: The year of birth of the patient
          type: string
        dayOfBirth:
          description: The day of birth of the patient
          type: string
        monthOfBirth:
          description: The month of birth of the patient
          type: string
        identifiers:
          items:
            $ref: '#/components/schemas/PatientVerifiedIdentifiers'
          type: array
      type: object
    PatientAddress:
      example:
        pincode: pincode
        line: line
        district: district
        state: state
      properties:
        line:
          description: The line of the patient address
          type: string
        district:
          description: The district of the patient address
          type: string
        state:
          description: The state of the patient address
          type: string
        pincode:
          description: The pincode of the patient address
          type: string
      type: object
    PatientVerifiedIdentifiers:
      example:
        type: type
        value: value
      properties:
        value:
          description: The value of the verified identifier
          type: string
        type:
          description: The type of the verified identifier
          type: string
      type: object
    PatientDiscoveryRequest:
      example:
        hipId: hipId
        requestId: 499a5a4a-7dda-4f20-9b67-e24589627061
        patient:
          verifiedIdentifiers:
          - type: null
            value: +919800083232
          - type: null
            value: +919800083232
          gender: null
          name: chandler bing
          unverifiedIdentifiers:
          - type: null
            value: +919800083232
          - type: null
            value: +919800083232
          id: <patient-id>@<consent-manager-id>
          yearOfBirth: 2000
        transactionId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        requestId:
          description: "a nonce, unique for each HTTP request."
          example: 499a5a4a-7dda-4f20-9b67-e24589627061
          format: uuid
          type: string
        timestamp:
          description: "Date time format in UTC, includes miliseconds YYYY-MM-DDThh:mm:ss.vZ"
          format: date-time
          type: string
        transactionId:
          description: correlation-Id for patient discovery and subsequent care context
            linkage
          format: uuid
          type: string
        patient:
          $ref: '#/components/schemas/PatientDiscoveryRequest_patient'
        hipId:
          type: string
      required:
      - patient
      - requestId
      - timestamp
      - transactionId
      type: object
      xml:
        name: PatientDiscoveryRequest
    PatientGender:
      enum:
      - M
      - F
      - O
      - U
      type: string
    TimestampSchema:
      description: "Date time format in UTC, includes miliseconds YYYY-MM-DDThh:mm:ss.vZ"
      format: date-time
      type: string
    Identifier:
      example:
        type: null
        value: +919800083232
      properties:
        type:
          $ref: '#/components/schemas/IdentifierType'
        value:
          example: +919800083232
          type: string
      type: object
      xml:
        name: Identifier
    IdentifierType:
      enum:
      - MR
      - MOBILE
      - NDHM_HEALTH_NUMBER
      - HEALTH_ID
      type: string
    _verify_otp_post_request:
      properties:
        loginHint:
          description: Hint for the type of authentication being performed
          type: string
        requestId:
          description: Unique identifier for the request
          type: string
        authCode:
          description: Authentication code to be verified
          type: string
        linkRefNumber:
          description: Unique id corresponding to the OTP request
          type: string
      required:
      - authCode
      - linkRefNumber
      - loginHint
      type: object
    _request_otp_post_request:
      properties:
        abhaAddress:
          description: Hint for the abhaAddress of the patient
          type: string
        requestId:
          description: Unique identifier for the request
          type: string
        patientReference:
          description: patient reference for the particular facility
          type: string
      required:
      - abhaAddress
      - patientReference
      - requestId
      type: object
    verifyOTP_request:
      properties:
        loginHint:
          enum:
          - hipLinking
          example: hipLinking
          type: string
        requestId:
          type: string
        authCode:
          type: string
      type: object
    linkCareContexts_request:
      properties:
        requestId:
          type: string
        requesterId:
          type: string
        abhaAddress:
          type: string
        authMode:
          enum:
          - DEMOGRAPHICS
          - MOBILE_OTP
          - AADHAAR_OTP
          example: DEMOGRAPHICS
          type: string
        hiTypes:
          items:
            enum:
            - DiagnosticReport
            - DischargeSummary
            - HealthDocumentRecord
            - ImmunizationRecord
            - OPConsultation
            - Prescription
            - WellnessRecord
            type: string
          type: array
        patient:
          $ref: '#/components/schemas/PatientWithCareContext'
      type: object
    SmsNotify_notification_hip:
      example:
        name: name
        id: id
      properties:
        name:
          type: string
        id:
          type: string
      type: object
    SmsNotify_notification:
      example:
        phoneNo: phoneNo
        hip:
          name: name
          id: id
      properties:
        phoneNo:
          type: string
        hip:
          $ref: '#/components/schemas/SmsNotify_notification_hip'
      type: object
    PatientDiscoveryRequest_patient:
      example:
        verifiedIdentifiers:
        - type: null
          value: +919800083232
        - type: null
          value: +919800083232
        gender: null
        name: chandler bing
        unverifiedIdentifiers:
        - type: null
          value: +919800083232
        - type: null
          value: +919800083232
        id: <patient-id>@<consent-manager-id>
        yearOfBirth: 2000
      properties:
        id:
          description: Identifier of patient at consent manager
          example: <patient-id>@<consent-manager-id>
          type: string
        verifiedIdentifiers:
          items:
            $ref: '#/components/schemas/Identifier'
          type: array
          xml:
            name: verifiedIdentifiers
            wrapped: true
        unverifiedIdentifiers:
          items:
            $ref: '#/components/schemas/Identifier'
          type: array
          xml:
            name: unverifiedIdentifiers
            wrapped: true
        name:
          example: chandler bing
          type: string
        gender:
          $ref: '#/components/schemas/PatientGender'
        yearOfBirth:
          example: 2000
          type: integer
      required:
      - gender
      - id
      - name
      - verifiedIdentifiers
      - yearOfBirth
      type: object

